### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by krame505** [melt-umn/ableC_sample_projects#3]
To be consistent with literally every other repository in melt-umn, this should be named `ableC-sample-projects`.  Objections?  

@ericvanwyk

**Comment by krame505** [comment]
Doing this will work around https://github.com/melt-umn/jenkins-lib/issues/8 for now, so any strong reasons *not* to make this change now?

**Comment by ericvanwyk** [comment]
No objections here - go for it.

**Comment by krame505** [comment]
Done.

**Comment by tedinski** [comment]
Just a thought: did you fix the name in other places it gets used? e.g. ableC-vm-artifact?

**Comment by krame505** [comment]
Yeah, let me know if I missed any.
